# -*- coding: utf-8 -*-
"""tugas_8_fuadmaulana0812.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17O96o59R0_rcLcfTrteiBHH4eF7rif3v
"""

# Import library yang dibutuhkan
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

# Membuka halaman kompas.com dan memasukan dalam objek Beautiful Soup
alamat = "https://www.kompas.com/"
html = urlopen(alamat)
data = BeautifulSoup(html, "html.parser")

# Mengambil judul berita yang terpopuler
table = data.findAll("div", {"class":"most__wrap"})[0]
rows = table.findAll("div", {"class":"most__list"})
result=[]
for row in rows:
  for cell in row.findAll("h4"):
    result.append(cell.get_text())

# Membuat DataFrame dari Judul Berita Terpopuler
df=pd.DataFrame(result,columns=["Judul Berita Terpopuler"])
print(df)

